name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., v1.0.0 or latest)'
        required: false
        default: latest
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG="${GITHUB_REF_NAME}"
          else
            TAG="${{ inputs.tag }}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE=ghcr.io/${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}
            ${{ steps.vars.outputs.IMAGE }}:latest
